%dw 2.0
output text/xml encoding="Windows-1252"
---
{
    "terminal" @(
        "type": "list",
        "end": "100",
        "name": "docum",
        "query": "CtaLan|TipoDoc|TpDoc=A1:B999|NrDoc=1:999999999"
    ): {
        "defcol": {
            "entry" @(
                "type": "table"
            ): {
                "defcol": {
                    "CtaLan.Ass.AssDigit" @(form: "%CtaLan.Ass.AssDigit"): {},
                    "CtaLan.Ass.AssTxt" @(form: "%CtaLan.Ass.AssTxt"): {},
                    "CtaLan.Ass.DataAss" @(form: "%CtaLan.Ass.DataAss"): {},
                    "CtaLan.Ass.HoraAss" @(form: "%CtaLan.Ass.HoraAss"): {},
                    "CtaLan.Ass.UserAss" @(form: "%CtaLan.Ass.UserAss"): {},
                    "CtaLan.Ass.VerCertif" @(form: "%CtaLan.Ass.VerCertif"): {},
                    "CtaLan.BP.ClassMapaBP" @(form: "%CtaLan.BP.ClassMapaBP"): {},
                    "CtaLan.BP.IsDocAdiant" @(form: "%CtaLan.BP.IsDocAdiant"): {},
                    "CtaLan.BP.MapaAtivFin" @(form: "%CtaLan.BP.MapaAtivFin"): {},
                    "CtaLan.BP.MapaBP2Cop" @(form: "%CtaLan.BP.MapaBP2Cop"): {},
                    "CtaLan.BP.MapaBPCta" @(form: "%CtaLan.BP.MapaBPCta"): {},
                    "CtaLan.BP.MapaContrap" @(form: "%CtaLan.BP.MapaContrap"): {},
                    "CtaLan.BP.MapaNPC2" @(form: "%CtaLan.BP.MapaNPC2"): {},
                    "CtaLan.C_C.AbrvMoeda" @(form: "%CtaLan.C_C.AbrvMoeda"): {},
                    "CtaLan.C_C.Agravam" @(form: "%CtaLan.C_C.Agravam"): {},
                    "CtaLan.C_C.AI_Ligacao" @(form: "%CtaLan.C_C.AI_Ligacao"): {},
                    "CtaLan.C_C.CambioAct" @(form: "%CtaLan.C_C.CambioAct"): {},
                    "CtaLan.C_C.CambioInf" @(form: "%CtaLan.C_C.CambioInf"): {},
                    "CtaLan.C_C.CambioInv" @(form: "%CtaLan.C_C.CambioInv"): {},
                    "CtaLan.C_C.CambioOrg" @(form: "%CtaLan.C_C.CambioOrg"): {},
                    "CtaLan.C_C.CodMoeda" @(form: "%CtaLan.C_C.CodMoeda"): {},
                    "CtaLan.C_C.CustNSuj" @(form: "%CtaLan.C_C.CustNSuj"): {},
                    "CtaLan.C_C.CustStd" @(form: "%CtaLan.C_C.CustStd"): {},
                    "CtaLan.C_C.CustSuj" @(form: "%CtaLan.C_C.CustSuj"): {},
                    "CtaLan.C_C.DataUltPag" @(form: "%CtaLan.C_C.DataUltPag"): {},
                    "CtaLan.C_C.DescMoeda" @(form: "%CtaLan.C_C.DescMoeda"): {},
                    "CtaLan.C_C.Desconto" @(form: "%CtaLan.C_C.Desconto"): {},
                    "CtaLan.C_C.DifCambio" @(form: "%CtaLan.C_C.DifCambio"): {},
                    "CtaLan.C_C.Imposto" @(form: "%CtaLan.C_C.Imposto"): {},
                    "CtaLan.C_C.ImpSelo" @(form: "%CtaLan.C_C.ImpSelo"): {},
                    "CtaLan.C_C.IVA" @(form: "%CtaLan.C_C.IVA"): {},
                    "CtaLan.C_C.Ligacoes" @(form: "%CtaLan.C_C.Ligacoes"): {},
                    "CtaLan.C_C.NmSerieGC" @(form: "%CtaLan.C_C.NmSerieGC"): {},
                    "CtaLan.C_C.NomeMoeda" @(form: "%CtaLan.C_C.NomeMoeda"): {},
                    "CtaLan.C_C.NomeVnd" @(form: "%CtaLan.C_C.NomeVnd"): {},
                    "CtaLan.C_C.NrFilial" @(form: "%CtaLan.C_C.NrFilial"): {},
                    "CtaLan.C_C.NrTotPagam" @(form: "%CtaLan.C_C.NrTotPagam"): {},
                    "CtaLan.C_C.NrVend" @(form: "%CtaLan.C_C.NrVend"): {},
                    "CtaLan.C_C.OrgInvoiceNo" @(form: "%CtaLan.C_C.OrgInvoiceNo"): {},
                    "CtaLan.C_C.Pend_Ligacao" @(form: "%CtaLan.C_C.Pend_Ligacao"): {},
                    "CtaLan.C_C.PMedIncump" @(form: "%CtaLan.C_C.PMedIncump"): {},
                    "CtaLan.C_C.PrMedPgDoc" @(form: "%CtaLan.C_C.PrMedPgDoc"): {},
                    "CtaLan.C_C.Relacoes" @(form: "%CtaLan.C_C.Relacoes"): {},
                    "CtaLan.C_C.RevMoeda" @(form: "%CtaLan.C_C.RevMoeda"): {},
                    "CtaLan.C_C.SaldoDoc" @(form: "%CtaLan.C_C.SaldoDoc"): {},
                    "CtaLan.C_C.SldMoeda" @(form: "%CtaLan.C_C.SldMoeda"): {},
                    "CtaLan.C_C.TemLigNC" @(form: "%CtaLan.C_C.TemLigNC"): {},
                    "CtaLan.C_C.TercOrg" @(form: "%CtaLan.C_C.TercOrg"): {},
                    "CtaLan.C_C.Tp_Ligacao" @(form: "%CtaLan.C_C.Tp_Ligacao"): {},
                    "CtaLan.C_C.TpDocOrg" @(form: "%CtaLan.C_C.TpDocOrg"): {},
                    "CtaLan.C_C.TpDOrgID" @(form: "%CtaLan.C_C.TpDOrgID"): {},
                    "CtaLan.C_C.TpDOrgIdR" @(form: "%CtaLan.C_C.TpDOrgIdR"): {},
                    "CtaLan.C_C.TxImpSelo" @(form: "%CtaLan.C_C.TxImpSelo"): {},
                    "CtaLan.C_C.ValMoeda" @(form: "%CtaLan.C_C.ValMoeda"): {},
                    "CtaLan.C_C.ValorOrg" @(form: "%CtaLan.C_C.ValorOrg"): {},
                    "CtaLan.C_C.ValRetencao" @(form: "%CtaLan.C_C.ValRetencao"): {},
                    "CtaLan.CDU.01" @(form: "%CtaLan.CDU.01"): {},
                    "CtaLan.CDU.02" @(form: "%CtaLan.CDU.02"): {},
                    "CtaLan.CDU.03" @(form: "%CtaLan.CDU.03"): {},
                    "CtaLan.CDU.04" @(form: "%CtaLan.CDU.04"): {},
                    "CtaLan.CDU.05" @(form: "%CtaLan.CDU.05"): {},
                    "CtaLan.CDU.06" @(form: "%CtaLan.CDU.06"): {},
                    "CtaLan.CDU.07" @(form: "%CtaLan.CDU.07"): {},
                    "CtaLan.CDU.08" @(form: "%CtaLan.CDU.08"): {},
                    "CtaLan.CDU.09" @(form: "%CtaLan.CDU.09"): {},
                    "CtaLan.CDU.10" @(form: "%CtaLan.CDU.10"): {},
                    "CtaLan.CDU.11" @(form: "%CtaLan.CDU.11"): {},
                    "CtaLan.CDU.12" @(form: "%CtaLan.CDU.12"): {},
                    "CtaLan.CDU.13" @(form: "%CtaLan.CDU.13"): {},
                    "CtaLan.CDU.14" @(form: "%CtaLan.CDU.14"): {},
                    "CtaLan.CDU.15" @(form: "%CtaLan.CDU.15"): {},
                    "CtaLan.CDU.16" @(form: "%CtaLan.CDU.16"): {},
                    "CtaLan.CDU.17" @(form: "%CtaLan.CDU.17"): {},
                    "CtaLan.CDU.18" @(form: "%CtaLan.CDU.18"): {},
                    "CtaLan.CDU.19" @(form: "%CtaLan.CDU.19"): {},
                    "CtaLan.CDU.20" @(form: "%CtaLan.CDU.20"): {},
                    "CtaLan.CDU.21" @(form: "%CtaLan.CDU.21"): {},
                    "CtaLan.CDU.22" @(form: "%CtaLan.CDU.22"): {},
                    "CtaLan.CDU.23" @(form: "%CtaLan.CDU.23"): {},
                    "CtaLan.CDU.24" @(form: "%CtaLan.CDU.24"): {},
                    "CtaLan.CDU.25" @(form: "%CtaLan.CDU.25"): {},
                    "CtaLan.CDU.26" @(form: "%CtaLan.CDU.26"): {},
                    "CtaLan.CDU.27" @(form: "%CtaLan.CDU.27"): {},
                    "CtaLan.CDU.28" @(form: "%CtaLan.CDU.28"): {},
                    "CtaLan.CDU.29" @(form: "%CtaLan.CDU.29"): {},
                    "CtaLan.CDU.30" @(form: "%CtaLan.CDU.30"): {},
                    "CtaLan.CDU.31" @(form: "%CtaLan.CDU.31"): {},
                    "CtaLan.CDU.32" @(form: "%CtaLan.CDU.32"): {},
                    "CtaLan.CDU.33" @(form: "%CtaLan.CDU.33"): {},
                    "CtaLan.CDU.34" @(form: "%CtaLan.CDU.34"): {},
                    "CtaLan.CDU.35" @(form: "%CtaLan.CDU.35"): {},
                    "CtaLan.CDU.36" @(form: "%CtaLan.CDU.36"): {},
                    "CtaLan.CDU.37" @(form: "%CtaLan.CDU.37"): {},
                    "CtaLan.CDU.38" @(form: "%CtaLan.CDU.38"): {},
                    "CtaLan.CDU.39" @(form: "%CtaLan.CDU.39"): {},
                    "CtaLan.CDU.40" @(form: "%CtaLan.CDU.40"): {},
                    "CtaLan.CDU.41" @(form: "%CtaLan.CDU.41"): {},
                    "CtaLan.CDU.42" @(form: "%CtaLan.CDU.42"): {},
                    "CtaLan.CDU.43" @(form: "%CtaLan.CDU.43"): {},
                    "CtaLan.CDU.44" @(form: "%CtaLan.CDU.44"): {},
                    "CtaLan.CDU.45" @(form: "%CtaLan.CDU.45"): {},
                    "CtaLan.CDU.46" @(form: "%CtaLan.CDU.46"): {},
                    "CtaLan.CDU.47" @(form: "%CtaLan.CDU.47"): {},
                    "CtaLan.CDU.48" @(form: "%CtaLan.CDU.48"): {},
                    "CtaLan.CDU.49" @(form: "%CtaLan.CDU.49"): {},
                    "CtaLan.CDU.50" @(form: "%CtaLan.CDU.50"): {},
                    "CtaLan.CDU.51" @(form: "%CtaLan.CDU.51"): {},
                    "CtaLan.CDU.52" @(form: "%CtaLan.CDU.52"): {},
                    "CtaLan.CDU.53" @(form: "%CtaLan.CDU.53"): {},
                    "CtaLan.CDU.54" @(form: "%CtaLan.CDU.54"): {},
                    "CtaLan.CDU.55" @(form: "%CtaLan.CDU.55"): {},
                    "CtaLan.CDU.56" @(form: "%CtaLan.CDU.56"): {},
                    "CtaLan.CDU.57" @(form: "%CtaLan.CDU.57"): {},
                    "CtaLan.CDU.58" @(form: "%CtaLan.CDU.58"): {},
                    "CtaLan.CDU.59" @(form: "%CtaLan.CDU.59"): {},
                    "CtaLan.CDU.60" @(form: "%CtaLan.CDU.60"): {},
                    "CtaLan.CDU.61" @(form: "%CtaLan.CDU.61"): {},
                    "CtaLan.CDU.62" @(form: "%CtaLan.CDU.62"): {},
                    "CtaLan.CDU.63" @(form: "%CtaLan.CDU.63"): {},
                    "CtaLan.Chq.Banco" @(form: "%CtaLan.Chq.Banco"): {},
                    "CtaLan.Chq.NaoPag" @(form: "%CtaLan.Chq.NaoPag"): {},
                    "CtaLan.Chq.Neg" @(form: "%CtaLan.Chq.Neg"): {},
                    "CtaLan.Chq.Pag" @(form: "%CtaLan.Chq.Pag"): {},
                    "CtaLan.Cta.AI_CCu" @(form: "%CtaLan.Cta.AI_CCu"): {},
                    "CtaLan.Cta.AI_Cta" @(form: "%CtaLan.Cta.AI_Cta"): {},
                    "CtaLan.Cta.AI_Terc" @(form: "%CtaLan.Cta.AI_Terc"): {},
                    "CtaLan.Cta.Conta" @(form: "%CtaLan.Cta.Conta"): {},
                    "CtaLan.Cta.CtaEd" @(form: "%CtaLan.Cta.CtaEd"): {},
                    "CtaLan.Cta.Filial" @(form: "%CtaLan.Cta.Filial"): {},
                    "CtaLan.Cta.NomeCCu" @(form: "%CtaLan.Cta.NomeCCu"): {},
                    "CtaLan.Cta.NomeCta" @(form: "%CtaLan.Cta.NomeCta"): {},
                    "CtaLan.Cta.NrCCuEd" @(form: "%CtaLan.Cta.NrCCuEd"): {},
                    "CtaLan.Cta.NrCCust" @(form: "%CtaLan.Cta.NrCCust"): {},
                    "CtaLan.Cta.NrTerc" @(form: "%CtaLan.Cta.NrTerc"): {},
                    "CtaLan.Cta.Prefixo" @(form: "%CtaLan.Cta.Prefixo"): {},
                    "CtaLan.Cta.TercID" @(form: "%CtaLan.Cta.TercID"): {},
                    "CtaLan.Data.DeltaDoc" @(form: "%CtaLan.Data.DeltaDoc"): {},
                    "CtaLan.Data.DeltaVenc" @(form: "%CtaLan.Data.DeltaVenc"): {},
                    "CtaLan.Data.Lanc" @(form: "%CtaLan.Data.Lanc"): {},
                    "CtaLan.Data.Origem" @(form: "%CtaLan.Data.Origem"): {},
                    "CtaLan.Data.PrevPagam" @(form: "%CtaLan.Data.PrevPagam"): {},
                    "CtaLan.Data.Venc" @(form: "%CtaLan.Data.Venc"): {},
                    "CtaLan.Data.VencC" @(form: "%CtaLan.Data.VencC"): {},
                    "CtaLan.Data.Vencido" @(form: "%CtaLan.Data.Vencido"): {},
                    "CtaLan.Diar.Descr" @(form: "%CtaLan.Diar.Descr"): {},
                    "CtaLan.Diar.Diario" @(form: "%CtaLan.Diar.Diario"): {},
                    "CtaLan.Diar.Mes" @(form: "%CtaLan.Diar.Mes"): {},
                    "CtaLan.Diar.NrArquivo" @(form: "%CtaLan.Diar.NrArquivo"): {},
                    "CtaLan.Diar.Numero" @(form: "%CtaLan.Diar.Numero"): {},
                    "CtaLan.Div.AdcTerAlerta" @(form: "%CtaLan.Div.AdcTerAlerta"): {},
                    "CtaLan.Div.AdcTerTipo" @(form: "%CtaLan.Div.AdcTerTipo"): {},
                    "CtaLan.Div.AdcTerTit" @(form: "%CtaLan.Div.AdcTerTit"): {},
                    "CtaLan.Div.AdcTerTxt" @(form: "%CtaLan.Div.AdcTerTxt"): {},
                    "CtaLan.Div.DebDirCod" @(form: "%CtaLan.Div.DebDirCod"): {},
                    "CtaLan.Div.DebDirErr" @(form: "%CtaLan.Div.DebDirErr"): {},
                    "CtaLan.Div.DebDireto" @(form: "%CtaLan.Div.DebDireto"): {},
                    "CtaLan.Div.DebDirHdr" @(form: "%CtaLan.Div.DebDirHdr"): {},
                    "CtaLan.Div.IDTransCashDriver" @(form: "%CtaLan.Div.IDTransCashDriver"): {},
                    "CtaLan.Div.NrMeioPgt" @(form: "%CtaLan.Div.NrMeioPgt"): {},
                    "CtaLan.Doc.Desc" @(form: "%CtaLan.Doc.Desc"): {},
                    "CtaLan.Doc.ID" @(form: "%CtaLan.Doc.ID"): {},
                    "CtaLan.Doc.InvoiceNo" @(form: "%CtaLan.Doc.InvoiceNo"): {},
                    "CtaLan.Doc.NrID" @(form: "%CtaLan.Doc.NrID"): {},
                    "CtaLan.Doc.Numero" @(form: "%CtaLan.Doc.Numero"): {},
                    "CtaLan.Doc.Ordem" @(form: "%CtaLan.Doc.Ordem"): {},
                    "CtaLan.Doc.Tipo" @(form: "%CtaLan.Doc.Tipo"): {},
                    "CtaLan.Doc.TipoID" @(form: "%CtaLan.Doc.TipoID"): {},
                    "CtaLan.Doc.TipoIdR" @(form: "%CtaLan.Doc.TipoIdR"): {},
                    "CtaLan.Doc.TpMovInt" @(form: "%CtaLan.Doc.TpMovInt"): {},
                    "CtaLan.Flag.Certificado" @(form: "%CtaLan.Flag.Certificado"): {},
                    "CtaLan.Flag.DocEstorno" @(form: "%CtaLan.Flag.DocEstorno"): {},
                    "CtaLan.Flag.EmitirRecibo" @(form: "%CtaLan.Flag.EmitirRecibo"): {},
                    "CtaLan.Flag.IdxDoc" @(form: "%CtaLan.Flag.IdxDoc"): {},
                    "CtaLan.Flag.IVACaixa" @(form: "%CtaLan.Flag.IVACaixa"): {},
                    "CtaLan.Flag.LcPend" @(form: "%CtaLan.Flag.LcPend"): {},
                    "CtaLan.Flag.MeioPag" @(form: "%CtaLan.Flag.MeioPag"): {},
                    "CtaLan.Flag.NaoActAcm" @(form: "%CtaLan.Flag.NaoActAcm"): {},
                    "CtaLan.Flag.NaoRec" @(form: "%CtaLan.Flag.NaoRec"): {},
                    "CtaLan.Flag.NaoSald" @(form: "%CtaLan.Flag.NaoSald"): {},
                    "CtaLan.Img.DescImg" @(form: "%CtaLan.Img.DescImg"): {},
                    "CtaLan.Img.ExistImg" @(form: "%CtaLan.Img.ExistImg"): {},
                    "CtaLan.Inf.ATCUD" @(form: "%CtaLan.Inf.ATCUD"): {},
                    "CtaLan.Inf.DataModif" @(form: "%CtaLan.Inf.DataModif"): {},
                    "CtaLan.Inf.HoraModif" @(form: "%CtaLan.Inf.HoraModif"): {},
                    "CtaLan.Inf.QRCode" @(form: "%CtaLan.Inf.QRCode"): {},
                    "CtaLan.Inf.TpDocNome" @(form: "%CtaLan.Inf.TpDocNome"): {},
                    "CtaLan.Inf.UserNm" @(form: "%CtaLan.Inf.UserNm"): {},
                    "CtaLan.Inf.UserNr" @(form: "%CtaLan.Inf.UserNr"): {},
                    "CtaLan.Lan.AIEfatura" @(form: "%CtaLan.Lan.AIEfatura"): {},
                    "CtaLan.Lan.ContEdi" @(form: "%CtaLan.Lan.ContEdi"): {},
                    "CtaLan.Lan.Contrap" @(form: "%CtaLan.Lan.Contrap"): {},
                    "CtaLan.Lan.Flags" @(form: "%CtaLan.Lan.Flags"): {},
                    "CtaLan.Lan.Flags2" @(form: "%CtaLan.Lan.Flags2"): {},
                    "CtaLan.Lan.Flags2B" @(form: "%CtaLan.Lan.Flags2B"): {},
                    "CtaLan.Lan.FlagsB" @(form: "%CtaLan.Lan.FlagsB"): {},
                    "CtaLan.Lan.FluxoCaixa" @(form: "%CtaLan.Lan.FluxoCaixa"): {},
                    "CtaLan.Lan.LkAnalGr" @(form: "%CtaLan.Lan.LkAnalGr"): {},
                    "CtaLan.Lan.MotDelDoc" @(form: "%CtaLan.Lan.MotDelDoc"): {},
                    "CtaLan.Lan.NaoAprov" @(form: "%CtaLan.Lan.NaoAprov"): {},
                    "CtaLan.Lan.NrIdFisc" @(form: "%CtaLan.Lan.NrIdFisc"): {},
                    "CtaLan.Lan.NrLiquid.Ano" @(form: "%CtaLan.Lan.NrLiquid.Ano"): {},
                    "CtaLan.Lan.NrLiquid.Data" @(form: "%CtaLan.Lan.NrLiquid.Data"): {},
                    "CtaLan.Lan.NrLiquid.Estancia" @(form: "%CtaLan.Lan.NrLiquid.Estancia"): {},
                    "CtaLan.Lan.NrLiquid.NrLiquid" @(form: "%CtaLan.Lan.NrLiquid.NrLiquid"): {},
                    "CtaLan.Lan.NrLiquid.Registo" @(form: "%CtaLan.Lan.NrLiquid.Registo"): {},
                    "CtaLan.Lan.Numero" @(form: "%CtaLan.Lan.Numero"): {},
                    "CtaLan.Lan.Obs" @(form: "%CtaLan.Lan.Obs", supressEmpty: "s"): {},
                    "CtaLan.Lan.ObsDocum" @(form: "%CtaLan.Lan.ObsDocum"): {},
                    "CtaLan.Lan.ProvConc" @(form: "%CtaLan.Lan.ProvConc"): {},
                    "CtaLan.Lan.Recapitulativo" @(form: "%CtaLan.Lan.Recapitulativo"): {},
                    "CtaLan.Lan.Refer" @(form: "%CtaLan.Lan.Refer"): {},
                    "CtaLan.Lan.TbMotDel" @(form: "%CtaLan.Lan.TbMotDel"): {},
                    "CtaLan.Let.Desconto" @(form: "%CtaLan.Let.Desconto"): {},
                    "CtaLan.Let.Devol" @(form: "%CtaLan.Let.Devol"): {},
                    "CtaLan.Let.Paga" @(form: "%CtaLan.Let.Paga"): {},
                    "CtaLan.Let.Recambio" @(form: "%CtaLan.Let.Recambio"): {},
                    "CtaLan.Let.RfrEfect" @(form: "%CtaLan.Let.RfrEfect"): {},
                    "CtaLan.Let.RfrPend" @(form: "%CtaLan.Let.RfrPend"): {},
                    "CtaLan.Let.Substit" @(form: "%CtaLan.Let.Substit"): {},
                    "CtaLan.MPag.Cod0" @(form: "%CtaLan.MPag.Cod0"): {},
                    "CtaLan.MPag.Cod1" @(form: "%CtaLan.MPag.Cod1"): {},
                    "CtaLan.MPag.Cod2" @(form: "%CtaLan.MPag.Cod2"): {},
                    "CtaLan.MPag.Cod3" @(form: "%CtaLan.MPag.Cod3"): {},
                    "CtaLan.MPag.Cod4" @(form: "%CtaLan.MPag.Cod4"): {},
                    "CtaLan.MPag.Nome0" @(form: "%CtaLan.MPag.Nome0"): {},
                    "CtaLan.MPag.Nome1" @(form: "%CtaLan.MPag.Nome1"): {},
                    "CtaLan.MPag.Nome2" @(form: "%CtaLan.MPag.Nome2"): {},
                    "CtaLan.MPag.Nome3" @(form: "%CtaLan.MPag.Nome3"): {},
                    "CtaLan.MPag.Nome4" @(form: "%CtaLan.MPag.Nome4"): {},
                    "CtaLan.MPag.ObsMPag0" @(form: "%CtaLan.MPag.ObsMPag0"): {},
                    "CtaLan.MPag.ObsMPag1" @(form: "%CtaLan.MPag.ObsMPag1"): {},
                    "CtaLan.MPag.ObsMPag2" @(form: "%CtaLan.MPag.ObsMPag2"): {},
                    "CtaLan.MPag.ObsMPag3" @(form: "%CtaLan.MPag.ObsMPag3"): {},
                    "CtaLan.MPag.ObsMPag4" @(form: "%CtaLan.MPag.ObsMPag4"): {},
                    "CtaLan.MPag.Valor0" @(form: "%CtaLan.MPag.Valor0"): {},
                    "CtaLan.MPag.Valor1" @(form: "%CtaLan.MPag.Valor1"): {},
                    "CtaLan.MPag.Valor2" @(form: "%CtaLan.MPag.Valor2"): {},
                    "CtaLan.MPag.Valor3" @(form: "%CtaLan.MPag.Valor3"): {},
                    "CtaLan.MPag.Valor4" @(form: "%CtaLan.MPag.Valor4"): {},
                    "CtaLan.RegIVA.Cod" @(form: "%CtaLan.RegIVA.Cod"): {},
                    "CtaLan.RegIVA.CodI" @(form: "%CtaLan.RegIVA.CodI"): {},
                    "CtaLan.RegIVA.Data" @(form: "%CtaLan.RegIVA.Data"): {},
                    "CtaLan.RegIVA.DataI" @(form: "%CtaLan.RegIVA.DataI"): {},
                    "CtaLan.RegIVA.PedidoPrev" @(form: "%CtaLan.RegIVA.PedidoPrev"): {},
                    "CtaLan.RegIVA.PedidoPrevI" @(form: "%CtaLan.RegIVA.PedidoPrevI"): {},
                    "CtaLan.Sibs.DataExpMB" @(form: "%CtaLan.Sibs.DataExpMB"): {},
                    "CtaLan.Sibs.Entidade" @(form: "%CtaLan.Sibs.Entidade"): {},
                    "CtaLan.Sibs.LastStatMB" @(form: "%CtaLan.Sibs.LastStatMB"): {},
                    "CtaLan.Sibs.Referencia" @(form: "%CtaLan.Sibs.Referencia"): {},
                    "CtaLan.TPA.InfTransf" @(form: "%CtaLan.TPA.InfTransf"): {},
                    "CtaLan.TPA.ReciboCli" @(form: "%CtaLan.TPA.ReciboCli"): {},
                    "CtaLan.TPA.ReciboOp" @(form: "%CtaLan.TPA.ReciboOp"): {},
                    "CtaLan.Val.DbCr" @(form: "%CtaLan.Val.DbCr"): {},
                    "CtaLan.Val.Estorno" @(form: "%CtaLan.Val.Estorno"): {},
                    "CtaLan.Val.IncIVA01" @(form: "%CtaLan.Val.IncIVA01"): {},
                    "CtaLan.Val.IncIVA02" @(form: "%CtaLan.Val.IncIVA02"): {},
                    "CtaLan.Val.IncIVA03" @(form: "%CtaLan.Val.IncIVA03"): {},
                    "CtaLan.Val.IncIVA04" @(form: "%CtaLan.Val.IncIVA04"): {},
                    "CtaLan.Val.IncIVA05" @(form: "%CtaLan.Val.IncIVA05"): {},
                    "CtaLan.Val.IncIVAEsp" @(form: "%CtaLan.Val.IncIVAEsp"): {},
                    "CtaLan.Val.TxIVA01" @(form: "%CtaLan.Val.TxIVA01"): {},
                    "CtaLan.Val.TxIVA02" @(form: "%CtaLan.Val.TxIVA02"): {},
                    "CtaLan.Val.TxIVA03" @(form: "%CtaLan.Val.TxIVA03"): {},
                    "CtaLan.Val.TxIVA04" @(form: "%CtaLan.Val.TxIVA04"): {},
                    "CtaLan.Val.TxIVA05" @(form: "%CtaLan.Val.TxIVA05"): {},
                    "CtaLan.Val.ValIVA01" @(form: "%CtaLan.Val.ValIVA01"): {},
                    "CtaLan.Val.ValIVA02" @(form: "%CtaLan.Val.ValIVA02"): {},
                    "CtaLan.Val.ValIVA03" @(form: "%CtaLan.Val.ValIVA03"): {},
                    "CtaLan.Val.ValIVA04" @(form: "%CtaLan.Val.ValIVA04"): {},
                    "CtaLan.Val.ValIVA05" @(form: "%CtaLan.Val.ValIVA05"): {},
                    "CtaLan.Val.ValLiqDoc" @(form: "%CtaLan.Val.ValLiqDoc"): {},
                    "CtaLan.Val.Valor" @(form: "%CtaLan.Val.Valor"): {},
                    "CtaLan.Val.ValorCr" @(form: "%CtaLan.Val.ValorCr"): {},
                    "CtaLan.Val.ValorDb" @(form: "%CtaLan.Val.ValorDb"): {}
                }
            },
            "onAcc" @(
                "type": "list",
                "name": "docRef",
                "supressEmpty": "s",
                "query": "CtaDoc|DocOrg|TpDoc={%CtaLan.Doc.TipoID}|NrDoc={%CtaLan.Doc.Numero}"
            ): {
                "defcol": {},
                "defAttr": {
                    "docID" @(form: "%CtaDoc.DocRegID/%CtaDoc.NrDocReg", "type": "text"): {},
                    "remitt" @(form: "%CtaDoc.ValorReg"): {}
                }
            }
        },
        "defAttr": {
            "docID" @(form: "%CtaLan.Doc.TipoID/%CtaLan.Doc.Numero"): {},
            "cpart" @(form: "%CtaLan.Lan.Contrap"): {},
            "retID" @(form: "s"): {},
            "status" @(form: "s"): {},
            "trans" @(form: "s"): {}
        }
    }
}
